name: Баг Репорт
description: Файл баг репорта
title: "[Баг]: "
labels: ["bug"]
assignees:
  - IruNil6
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что выделяете время для заполнения баг репорта!
  - type: dropdown
    id: function
    attributes:
      label: Функция
      description: Во время использования какой функции произошел данный баг?
      options:
        - Статистика
        - Динамические приватные каналы
        - Одна из базовых команд
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Что произошло?
      description: Расскажите подробно что где и как произошло?
      placeholder: Рассказывай!
      value: "Случился баг!"
    validations:
      required: true
  - type: dropdown
    id: errors
    attributes:
      label: Какую ошибку выдал вам бот?
      options:
        - Ошибка 0001
        - Ошибка 0002
        - Ошибка 0003
        - Ошибка 0004
        - Ошибка 0005
        - Ошибка 0006
        - Ошибка 0007
        - Ошибка 0008
        - Ошибка 0009
        - Ошибка 0010
        - Ошибка 0011
        - Ошибка 0012
        - Ошибка 0013
        - Ошибка 0014
        - Ошибка 0015
        - Ошибка 0016
        - Ошибка 0017
        - Ошибка 0018
        - Ошибка 0019
        - Ошибка 0020
  - type: checkboxes
    id: terms
    attributes:
      label: Правила Поведения
      description: Присылая данный issue нам, вы подтверждаете [Правила Поведения](https://cdns.team)
      options:
        - label: Я согласен с Правилами Поведения данного проекта.
          required: true
